import { Component } from '@angular/core';

@Component({
  selector: 'app-people',
  templateUrl: './people.component.html',
  styleUrls: ['./people.component.css'],
})
export class PeopleComponent {
  people = [
    {
      id: 1,
      firstName: 'Александр',
      lastName: 'Иванов',
      age: 34,
      occupation: 'Разработчик',
      salary: 120000,
      city: 'Москва',
      birthDate: new Date('1990-05-15'),
    },
    {
      id: 2,
      firstName: 'Елена',
      lastName: 'Петрова',
      age: 28,
      occupation: 'Дизайнер',
      salary: 95000,
      city: 'Санкт-Петербург',
      birthDate: new Date('1996-11-23'),
    },
    {
      id: 3,
      firstName: 'Максим',
      lastName: 'Сидоров',
      age: 42,
      occupation: 'Менеджер',
      salary: 150000,
      city: 'Казань',
      birthDate: new Date('1982-08-07'),
    },
    {
      id: 4,
      firstName: 'Анна',
      lastName: 'Козлова',
      age: 25,
      occupation: 'Маркетолог',
      salary: 85000,
      city: 'Новосибирск',
      birthDate: new Date('1999-03-29'),
    },
    {
      id: 5,
      firstName: 'Сергей',
      lastName: 'Морозов',
      age: 39,
      occupation: 'Аналитик',
      salary: 110000,
      city: 'Екатеринбург',
      birthDate: new Date('1985-12-10'),
    },
    {
      id: 6,
      firstName: 'Ольга',
      lastName: 'Смирнова',
      age: 31,
      occupation: 'Врач',
      salary: 105000,
      city: 'Самара',
      birthDate: new Date('1993-07-18'),
    },
    {
      id: 7,
      firstName: 'Дмитрий',
      lastName: 'Соколов',
      age: 37,
      occupation: 'Архитектор',
      salary: 130000,
      city: 'Нижний Новгород',
      birthDate: new Date('1987-09-02'),
    },
    {
      id: 8,
      firstName: 'Наталья',
      lastName: 'Волкова',
      age: 29,
      occupation: 'Бухгалтер',
      salary: 90000,
      city: 'Краснодар',
      birthDate: new Date('1995-04-14'),
    },
  ];
}
